//============================ Health Routes =======================//

###
GET http://localhost:3000/health


//========================== UrlAddres Routes ======================//

###
POST http://localhost:3000/encode
Content-Type: application/json

{
  "url": "yahoo.com"
}


###
POST http://localhost:3000/decode
Content-Type: application/json

{
  "url": "http://shortest.dev/KEEt3U"
}
