version: '3.4'

networks:
  production:
    driver: bridge

services:
  api_production:
    build:
      context: .
      dockerfile: prod.Dockerfile
    networks:
      - production
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DB_HOST=db_production
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - TYPEORM_MIGRATION=${TYPEORM_MIGRATION}
      - TYPEORM_ENTITIES=${TYPEORM_ENTITIES}
      - TYPEORM_MIGRATION_DIR=${TYPEORM_MIGRATION_DIR}
      - TYPEORM_ENTITIES_DIR=${TYPEORM_ENTITIES_DIR}
      - BASE_URL=${BASE_URL}
    depends_on:
      - db_production

  db_production:
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - production
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
